"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { fetchPublicReport, type PublicReport } from "@/modules/ai-observability/api/reports.api";

export default function SharedReportPage() {
  const token = String(useParams()?.token || "");
  const [report, setReport] = useState<PublicReport | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "missing">("loading");

  useEffect(() => {
    let active = true;
    fetchPublicReport(token).then((result) => {
      if (!active) return;
      if (result) {
        setReport(result);
        setState("ready");
      } else {
        setState("missing");
      }
    });
    return () => {
      active = false;
    };
  }, [token]);

  if (state === "loading") {
    return <div className="flex min-h-screen items-center justify-center text-sm text-muted-foreground">Loading shared report…</div>;
  }

  if (state === "missing" || !report) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-2 text-center">
        <h1 className="text-lg font-semibold">Report unavailable</h1>
        <p className="text-sm text-muted-foreground">This shared report has expired, been revoked, or does not exist.</p>
      </div>
    );
  }

  const entries = Object.entries(report.snapshot || {});

  return (
    <div className="mx-auto min-h-screen max-w-3xl px-6 py-12">
      <header className="mb-6 border-b pb-4">
        <p className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">
          Cloudcam · {report.reportType} report
        </p>
        <h1 className="mt-1 text-2xl font-bold tracking-tight">{report.title}</h1>
        {report.description && <p className="mt-1 text-sm text-muted-foreground">{report.description}</p>}
        <p className="mt-2 text-[11px] text-muted-foreground">
          Shared snapshot · captured {new Date(report.createdAt).toLocaleString()}
        </p>
      </header>

      {entries.length === 0 ? (
        <p className="text-sm text-muted-foreground">This report has no captured metrics.</p>
      ) : (
        <div className="grid gap-3 sm:grid-cols-2">
          {entries.map(([key, value]) => (
            <div key={key} className="rounded-lg border bg-secondary/10 p-4">
              <p className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">{key}</p>
              <p className="mt-1 break-words text-lg font-semibold">
                {typeof value === "object" ? JSON.stringify(value) : String(value)}
              </p>
            </div>
          ))}
        </div>
      )}

      <footer className="mt-10 border-t pt-4 text-center text-[11px] text-muted-foreground">
        Read-only snapshot generated by Cloudcam AI Observability.
      </footer>
    </div>
  );
}
