import { z } from "zod";
import type { CloudProvider, ServiceId } from "../types";

export const SERVICE_ICONS: Record<string, string> = {
  github: "Github",
  ec2: "Server",
  s3: "HardDrive",
  rds: "Database",
  lambda: "Zap",
  dynamodb: "Database",
  apigateway: "Cloud",
  ecs: "Container",
  eks: "Boxes",
  dockerhub: "Container",
  ecr: "FolderGit",
  azure_acr: "FolderGit",
  gcp_artifact_registry: "FolderGit",
  eip: "Globe",
  azure_pip: "Globe",
  gcp_ip: "Globe",
  sg: "Shield",
  azure_nsg: "Shield",
  gcp_firewall: "Shield",
  tg: "Network",
  azure_tg: "Network",
  gcp_tg: "Network",
  ebs: "HardDrive",
  azure_disk: "HardDrive",
  gcp_disk: "HardDrive",
  azure_vm: "Server",
  azure_storage: "HardDrive",
  azure_sql: "Database",
  azure_function: "Zap",
  azure_vnet: "Cloud",
  aws_vpc: "Cloud",
  gcp_vpc: "Cloud",
  vpc: "Cloud",
  gcp_compute: "Server",
  gcp_storage: "HardDrive",
  gcp_sql: "Database",
  gcp_function: "Zap",
  gcp_gke: "Boxes",
  azure_aks: "Boxes",
  elb: "Network",
  azure_lb: "Network",
  gcp_lb: "Network",
  asg: "Gauge",
  azure_vmss: "Gauge",
  gcp_mig: "Gauge",
  cloudfront: "Globe",
  azure_cdn: "Globe",
  gcp_cdn: "Globe",
};

export const SERVICE_COLORS: Record<string, { bg: string; border: string; icon: string; accent: string }> = {
  github: { bg: "bg-slate-500/10", border: "border-slate-500/40", icon: "text-slate-700 dark:text-slate-300", accent: "#64748b" },
  dockerhub: { bg: "bg-sky-500/10", border: "border-sky-500/40", icon: "text-sky-500", accent: "#0db7ed" },
  ecr: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#4f46e5" },
  azure_acr: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#4f46e5" },
  gcp_artifact_registry: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#4f46e5" },
  eip: { bg: "bg-yellow-500/10", border: "border-yellow-500/40", icon: "text-yellow-500", accent: "#eab308" },
  azure_pip: { bg: "bg-yellow-500/10", border: "border-yellow-500/40", icon: "text-yellow-500", accent: "#eab308" },
  gcp_ip: { bg: "bg-yellow-500/10", border: "border-yellow-500/40", icon: "text-yellow-500", accent: "#eab308" },
  sg: { bg: "bg-rose-500/10", border: "border-rose-500/40", icon: "text-rose-500", accent: "#f43f5e" },
  azure_nsg: { bg: "bg-rose-500/10", border: "border-rose-500/40", icon: "text-rose-500", accent: "#f43f5e" },
  gcp_firewall: { bg: "bg-rose-500/10", border: "border-rose-500/40", icon: "text-rose-500", accent: "#f43f5e" },
  tg: { bg: "bg-orange-500/10", border: "border-orange-500/40", icon: "text-orange-500", accent: "#f97316" },
  azure_tg: { bg: "bg-orange-500/10", border: "border-orange-500/40", icon: "text-orange-500", accent: "#f97316" },
  gcp_tg: { bg: "bg-orange-500/10", border: "border-orange-500/40", icon: "text-orange-500", accent: "#f97316" },
  ebs: { bg: "bg-slate-500/10", border: "border-slate-500/40", icon: "text-slate-500", accent: "#64748b" },
  azure_disk: { bg: "bg-slate-500/10", border: "border-slate-500/40", icon: "text-slate-500", accent: "#64748b" },
  gcp_disk: { bg: "bg-slate-500/10", border: "border-slate-500/40", icon: "text-slate-500", accent: "#64748b" },
  ec2: { bg: "bg-blue-500/10", border: "border-blue-500/40", icon: "text-blue-500", accent: "#3b82f6" },
  s3: { bg: "bg-emerald-500/10", border: "border-emerald-500/40", icon: "text-emerald-500", accent: "#10b981" },
  rds: { bg: "bg-amber-500/10", border: "border-amber-500/40", icon: "text-amber-500", accent: "#f59e0b" },
  lambda: { bg: "bg-violet-500/10", border: "border-violet-500/40", icon: "text-violet-500", accent: "#8b5cf6" },
  dynamodb: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#6366f1" },
  apigateway: { bg: "bg-pink-500/10", border: "border-pink-500/40", icon: "text-pink-500", accent: "#ec4899" },
  ecs: { bg: "bg-orange-500/10", border: "border-orange-500/40", icon: "text-orange-500", accent: "#f97316" },
  eks: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#06b6d4" },
  azure_vm: { bg: "bg-sky-500/10", border: "border-sky-500/40", icon: "text-sky-500", accent: "#0078d4" },
  azure_storage: { bg: "bg-teal-500/10", border: "border-teal-500/40", icon: "text-teal-500", accent: "#00a4ef" },
  azure_sql: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#5c2d91" },
  azure_function: { bg: "bg-amber-500/10", border: "border-amber-500/40", icon: "text-amber-500", accent: "#ffb900" },
  azure_vnet: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#50e6ff" },
  aws_vpc: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#50e6ff" },
  gcp_vpc: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#50e6ff" },
  vpc: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#50e6ff" },
  gcp_compute: { bg: "bg-blue-500/10", border: "border-blue-500/40", icon: "text-blue-500", accent: "#4285f4" },
  gcp_storage: { bg: "bg-green-500/10", border: "border-green-500/40", icon: "text-green-500", accent: "#34a853" },
  gcp_sql: { bg: "bg-amber-500/10", border: "border-amber-500/40", icon: "text-amber-500", accent: "#fbbc04" },
  gcp_function: { bg: "bg-sky-500/10", border: "border-sky-500/40", icon: "text-sky-500", accent: "#06b6d4" },
  gcp_gke: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#6366f1" },
  azure_aks: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#6366f1" },
  elb: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#06b6d4" },
  azure_lb: { bg: "bg-teal-500/10", border: "border-teal-500/40", icon: "text-teal-500", accent: "#0d9488" },
  gcp_lb: { bg: "bg-indigo-500/10", border: "border-indigo-500/40", icon: "text-indigo-500", accent: "#6366f1" },
  asg: { bg: "bg-orange-500/10", border: "border-orange-500/40", icon: "text-orange-500", accent: "#f97316" },
  azure_vmss: { bg: "bg-cyan-500/10", border: "border-cyan-500/40", icon: "text-cyan-500", accent: "#00a4ef" },
  gcp_mig: { bg: "bg-emerald-500/10", border: "border-emerald-500/40", icon: "text-emerald-500", accent: "#34a853" },
  cloudfront: { bg: "bg-purple-500/10", border: "border-purple-500/40", icon: "text-purple-500", accent: "#a855f7" },
  azure_cdn: { bg: "bg-purple-500/10", border: "border-purple-500/40", icon: "text-purple-500", accent: "#a855f7" },
  gcp_cdn: { bg: "bg-purple-500/10", border: "border-purple-500/40", icon: "text-purple-500", accent: "#a855f7" },
};

export const DockerHubConfigSchema = z.object({
  repository: z.string().default("library/nginx"),
  tag: z.string().default("latest"),
  username: z.string().default("").optional(),
  password: z.string().default("").optional(),
  appPort: z.coerce.number().int().min(1).max(65535).default(8080),
  containerPort: z.coerce.number().int().min(0).max(65535).default(0).optional(),
});

export const GithubConfigSchema = z.object({
  gitUrl: z.string().default("https://github.com/expressjs/express.git"),
  gitBranch: z.string().default("master"),
  gitToken: z.string().default("").optional(),
  projectType: z.enum(["generic_node", "node_api", "vite_spa", "mern", "nextjs", "docker"]).default("generic_node"),
  appRuntime: z.enum(["nodejs20", "python3", "docker"]).default("nodejs20"),
  buildCommand: z.string().default("npm install"),
  startCommand: z.string().default("node index.js"),
  appPort: z.coerce.number().int().min(1).max(65535).default(3000),
  frontendDir: z.string().default("").optional(),
  backendDir: z.string().default("").optional(),
  apiPath: z.string().default("/api"),
  backendPort: z.coerce.number().int().min(1).max(65535).default(5000),
});

export const SecurityRuleSchema = z.object({
  type: z.enum(["ingress", "egress"]).default("ingress"),
  fromPort: z.coerce.number().int().min(1).max(65535).default(80),
  toPort: z.coerce.number().int().min(1).max(65535).default(80),
  protocol: z.string().default("tcp"),
  cidrBlocks: z.string().default("0.0.0.0/0"),
});

export type DockerHubConfig = z.infer<typeof DockerHubConfigSchema>;
export type GithubConfig = z.infer<typeof GithubConfigSchema>;

export interface ServiceDefinition {
  id: ServiceId;
  provider: CloudProvider;
  label: string;
  description: string;
  icon: string;
  colorKey: string;
  defaultConfig: Record<string, unknown>;
  schema: z.ZodObject<any>;
}

export const commonServices: ServiceDefinition[] = [
  {
    id: "github",
    provider: "aws",
    label: "GitHub Repository",
    description: "Connect a GitHub repository to deploy code",
    icon: "Github",
    colorKey: "github",
    defaultConfig: GithubConfigSchema.parse({}),
    schema: GithubConfigSchema,
  },
  {
    id: "dockerhub",
    provider: "aws",
    label: "Docker Hub",
    description: "Connect a Docker Hub repository or pull container images",
    icon: "Container",
    colorKey: "dockerhub",
    defaultConfig: DockerHubConfigSchema.parse({}),
    schema: DockerHubConfigSchema,
  },
  {
    id: "github",
    provider: "azure",
    label: "GitHub Repository",
    description: "Connect a GitHub repository to deploy code",
    icon: "Github",
    colorKey: "github",
    defaultConfig: GithubConfigSchema.parse({}),
    schema: GithubConfigSchema,
  },
  {
    id: "dockerhub",
    provider: "azure",
    label: "Docker Hub",
    description: "Connect a Docker Hub repository or pull container images",
    icon: "Container",
    colorKey: "dockerhub",
    defaultConfig: DockerHubConfigSchema.parse({}),
    schema: DockerHubConfigSchema,
  },
  {
    id: "github",
    provider: "gcp",
    label: "GitHub Repository",
    description: "Connect a GitHub repository to deploy code",
    icon: "Github",
    colorKey: "github",
    defaultConfig: GithubConfigSchema.parse({}),
    schema: GithubConfigSchema,
  },
  {
    id: "dockerhub",
    provider: "gcp",
    label: "Docker Hub",
    description: "Connect a Docker Hub repository or pull container images",
    icon: "Container",
    colorKey: "dockerhub",
    defaultConfig: DockerHubConfigSchema.parse({}),
    schema: DockerHubConfigSchema,
  },
];
