export {
  gcpSetupPost,
  gcpSaveConnectionPost,
  gcpUpdateBillingPost,
  gcpBillingGet,
  gcpLogsGet,
  gcpMetricsGet,
  gcpResourcesGet,
  gcpInsightsGet,
  gcpSecurityGet,
  gcpAlarmsGet,
  gcpAlarmsPost,
  gcpAlarmDelete,
  gcpAlarmTogglePatch,
  gcpDefaultAlarmsGet,
  gcpDefaultAlarmsPost,
  gcpAlarmMetadataServicesGet,
  gcpAlarmMetadataResourcesGet,
  gcpAlarmMetadataActionGroupsGet,
} from "../../modules/gcp/controllers/index.controller";
