export function slugSimulationName(name?: string | null): string {
  return (
    (name || "simulation")
      .replace(/[^a-z0-9]/gi, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .toLowerCase() || "simulation"
  );
}

interface EcrOutput {
  url: string;
  registry: string;
  repoName: string;
  tag: string;
  nodeLabel: string;
}

export const generateBashScript = (
  registryLabel: string,
  name: string,
  ecrOutputs: EcrOutput[],
  provider: string,
  formRegion: string
) => {
  let content = `#!/bin/bash\n`;
  content += `# Automated ${registryLabel} Push Script generated by Cloudcam\n`;
  content += `set -e\n\n`;
  content += `echo "========================================================="\n`;
  content += `echo "Starting ${registryLabel} Push Process for ${slugSimulationName(name)}"\n`;
  content += `echo "========================================================="\n\n`;

  if (ecrOutputs.length > 0) {
    const firstRegistry = ecrOutputs[0].registry;
    if (provider === "azure") {
      const acrName = firstRegistry.replace(".azurecr.io", "");
      content += `echo "Step 1: Authenticating Docker with Azure ACR..."\n`;
      content += `az acr login --name ${acrName}\n\n`;
    } else if (provider === "gcp") {
      const locationMatch = ecrOutputs[0].url.match(/^([^-]+-[^-]+)-docker\.pkg\.dev/);
      const location = locationMatch ? locationMatch[1] : formRegion;
      content += `echo "Step 1: Authenticating Docker with Artifact Registry..."\n`;
      content += `gcloud auth configure-docker ${location}-docker.pkg.dev\n\n`;
    } else {
      content += `echo "Step 1: Authenticating Docker with ECR..."\n`;
      content += `aws ecr get-login-password --region ${formRegion} | docker login --username AWS --password-stdin ${firstRegistry}\n\n`;
    }
  }

  ecrOutputs.forEach((ecr, index) => {
    content += `echo "Step 2.${index + 1}: Building local Docker image for ${ecr.nodeLabel}..."\n`;
    content += `docker build -t ${ecr.repoName}:${ecr.tag} .\n\n`;

    content += `echo "Step 3.${index + 1}: Tagging image for ${registryLabel}..."\n`;
    content += `docker tag ${ecr.repoName}:${ecr.tag} ${ecr.url}:${ecr.tag}\n\n`;

    content += `echo "Step 4.${index + 1}: Pushing image to ${registryLabel}..."\n`;
    content += `docker push ${ecr.url}:${ecr.tag}\n\n`;
  });

  content += `echo "========================================================="\n`;
  content += `echo "SUCCESS: All images pushed successfully!"\n`;
  content += `echo "Please return to the Cloudcam dashboard and click"\n`;
  content += `echo "'Confirm Image Uploaded & Resume' to finish deployment."\n`;
  content += `echo "========================================================="\n`;

  return content;
};

export const generatePowerShellScript = (
  registryLabel: string,
  name: string,
  ecrOutputs: EcrOutput[],
  provider: string,
  formRegion: string
) => {
  let content = `# Automated ${registryLabel} Push Script generated by Cloudcam\n`;
  content += `$ErrorActionPreference = "Stop"\n\n`;
  content += `Write-Host "=========================================================" -ForegroundColor Cyan\n`;
  content += `Write-Host "Starting ${registryLabel} Push Process for ${slugSimulationName(name)}" -ForegroundColor Cyan\n`;
  content += `Write-Host "=========================================================" -ForegroundColor Cyan\n\n`;

  if (ecrOutputs.length > 0) {
    const firstRegistry = ecrOutputs[0].registry;
    if (provider === "azure") {
      const acrName = firstRegistry.replace(".azurecr.io", "");
      content += `Write-Host "Step 1: Authenticating Docker with Azure ACR..." -ForegroundColor Yellow\n`;
      content += `az acr login --name ${acrName}\n\n`;
    } else if (provider === "gcp") {
      const locationMatch = ecrOutputs[0].url.match(/^([^-]+-[^-]+)-docker\.pkg\.dev/);
      const location = locationMatch ? locationMatch[1] : formRegion;
      content += `Write-Host "Step 1: Authenticating Docker with Artifact Registry..." -ForegroundColor Yellow\n`;
      content += `gcloud auth configure-docker ${location}-docker.pkg.dev\n\n`;
    } else {
      content += `Write-Host "Step 1: Authenticating Docker with ECR..." -ForegroundColor Yellow\n`;
      content += `aws ecr get-login-password --region ${formRegion} | docker login --username AWS --password-stdin ${firstRegistry}\n\n`;
    }
  }

  ecrOutputs.forEach((ecr, index) => {
    content += `Write-Host "Step 2.${index + 1}: Building local Docker image for ${ecr.nodeLabel}..." -ForegroundColor Yellow\n`;
    content += `docker build -t ${ecr.repoName}:${ecr.tag} .\n\n`;

    content += `Write-Host "Step 3.${index + 1}: Tagging image for ${registryLabel}..." -ForegroundColor Yellow\n`;
    content += `docker tag ${ecr.repoName}:${ecr.tag} ${ecr.url}:${ecr.tag}\n\n`;

    content += `Write-Host "Step 4.${index + 1}: Pushing image to ${registryLabel}..." -ForegroundColor Yellow\n`;
    content += `docker push ${ecr.url}:${ecr.tag}\n\n`;
  });

  content += `Write-Host "=========================================================" -ForegroundColor Green\n`;
  content += `Write-Host "SUCCESS: All images pushed successfully!" -ForegroundColor Green\n`;
  content += `Write-Host "Please return to the Cloudcam dashboard and click" -ForegroundColor Green\n`;
  content += `Write-Host "'Confirm Image Uploaded & Resume' to finish deployment." -ForegroundColor Green\n`;
  content += `Write-Host "=========================================================" -ForegroundColor Green\n`;

  return content;
};
