import {
  Activity,
  AlertTriangle,
  Bell,
  Brain,
  Container,
  Cpu,
  Database,
  DollarSign,
  Eye,
  FileText,
  Github,
  Globe,
  HardDrive,
  Hash,
  History,
  Key,
  LayoutDashboard,
  Lightbulb,
  Mail,
  Network,
  Radar,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  TestTube,
  TrendingDown,
  Zap,
} from "@/icons";
import { SERVICE_REGISTRY } from "@/lib/services/registry";
import { NavGroup, NavItem } from "../types";

/** Cloud-provider display names (AWS/Azure/GCP) for a service href. */
function providerAliases(href: string): string[] {
  const serviceId = href.split("/").pop();
  const config = serviceId ? SERVICE_REGISTRY[serviceId] : undefined;
  if (!config) return [];
  return [
    config.displayName,
    config.azureDisplayName,
    config.gcpDisplayName,
  ].filter((name): name is string => Boolean(name));
}

export const navGroups: NavGroup[] = [
  {
    label: "Overview",
    section: "main",
    items: [
      {
        href: "/dashboard",
        label: "Overview",
        icon: LayoutDashboard,
        category: "Overview",
        description: "Command center across all clouds and services",
        keywords: ["dashboard", "command center", "home", "start", "summary"],
      },
      {
        href: "/watchdog",
        label: "Watchdog",
        icon: Radar,
        category: "Overview",
        description: "Live monitoring and anomaly detection",
        keywords: ["monitor", "watch", "anomaly", "detection", "alerts"],
      },
      {
        href: "/recommendations",
        label: "Insights",
        icon: Sparkles,
        category: "Overview",
        description: "AI-generated optimization recommendations",
        keywords: ["recommendations", "optimization", "advice", "suggestions"],
      },
      {
        href: "/simulations/live-canvas",
        label: "Simulation",
        icon: TestTube,
        category: "Overview",
        description: "Model infrastructure changes before you ship them",
        keywords: ["simulations", "live", "running", "canvas", "what-if"],
      },
      {
        href: "/vps-logs",
        label: "VPS Logs",
        icon: FileText,
        category: "Overview",
        description: "Stream and search server logs",
        keywords: ["logs", "server logs", "vps", "syslog", "agent"],
      },
      {
        href: "/resize-migration",
        label: "Resize & Migration",
        icon: Zap,
        category: "Overview",
        description: "Right-size and clone instances across regions",
        keywords: [
          "migration",
          "clone",
          "resize",
          "rightsizing",
          "operations",
          "move",
        ],
      },
    ],
  },
  {
    label: "Compute",
    section: "compute",
    items: [
      {
        href: "/dashboards/ec2",
        label: "EC2 Instances",
        icon: Server,
        description: "Virtual machines and their utilization",
        keywords: ["elastic compute", "instances", "vm", "virtual machine"],
      },
      {
        href: "/dashboards/lambda",
        label: "Lambda",
        icon: Zap,
        description: "Serverless functions",
        keywords: ["serverless", "functions", "faas"],
      },
      {
        href: "/dashboards/eks",
        label: "EKS Clusters",
        icon: Container,
        description: "Managed Kubernetes clusters",
        keywords: ["kubernetes", "k8s", "clusters", "containers"],
      },
      {
        href: "/dashboards/ecs",
        label: "ECS Services",
        icon: Container,
        description: "Container services and tasks",
        keywords: ["containers", "fargate", "tasks", "docker"],
      },
      {
        href: "/dashboards/amplify",
        label: "Amplify",
        icon: Globe,
        description: "Frontend hosting and deployments",
        keywords: ["hosting", "web apps", "frontend", "deploy"],
      },
    ],
  },
  {
    label: "Data",
    section: "data",
    items: [
      {
        href: "/dashboards/rds",
        label: "RDS",
        icon: Database,
        description: "Managed relational databases",
        keywords: ["database", "postgres", "mysql", "sql", "relational"],
      },
      {
        href: "/dashboards/dynamodb",
        label: "DynamoDB",
        icon: Database,
        description: "Managed NoSQL key-value store",
        keywords: ["nosql", "database", "key value", "tables"],
      },
      {
        href: "/dashboards/s3",
        label: "S3 Buckets",
        icon: HardDrive,
        description: "Object storage buckets",
        keywords: ["object storage", "bucket", "blob", "files", "storage"],
      },
    ],
  },
  {
    label: "Infrastructure",
    section: "infrastructure",
    items: [
      {
        href: "/dashboards/networking",
        label: "Networking",
        icon: Network,
        description: "VPCs, subnets and load balancers",
        keywords: [
          "vpc",
          "subnets",
          "load balancer",
          "elb",
          "route",
          "gateway",
        ],
      },
      {
        href: "/dashboards/security",
        label: "Cloud Security",
        icon: Shield,
        description: "IAM, GuardDuty and Security Hub findings",
        keywords: [
          "iam",
          "guardduty",
          "security hub",
          "findings",
          "threats",
          "posture",
        ],
      },
    ],
  },

  {
    label: "AI Observability",
    section: "ai",
    items: [
      {
        href: "/ai-observability",
        label: "AI Observability Overview",
        icon: Eye,
        category: "AI · Monitoring",
        description: "Health, cost and quality across your LLM apps",
        aliases: ["llmops", "ai monitoring"],
        keywords: ["ai observation", "ai observability", "llm", "overview"],
      },
      {
        href: "/ai-observability/traces",
        label: "Trace Explorer",
        icon: Activity,
        category: "AI · Monitoring",
        description: "Inspect individual LLM calls, spans and latency",
        keywords: ["traces", "spans", "waterfall", "latency", "debug"],
      },
      {
        href: "/ai-observability/models",
        label: "Model Usage",
        icon: Cpu,
        category: "AI · Monitoring",
        description: "Usage and performance by model and provider",
        keywords: ["model usage", "providers", "openai", "anthropic", "gpt"],
      },
      {
        href: "/ai-observability/cost",
        label: "AI Cost & Tokens",
        icon: DollarSign,
        category: "AI · Cost",
        description: "Token spend broken down by model, app and user",
        keywords: ["tokens", "spend", "ai cost", "llm cost", "pricing"],
      },
      {
        href: "/ai-observability/errors",
        label: "AI Errors",
        icon: AlertTriangle,
        category: "AI · Monitoring",
        description: "Failed and errored LLM calls",
        keywords: ["failures", "errors", "exceptions", "rate limits"],
      },
      {
        href: "/ai-observability/alerts",
        label: "AI Alerts",
        icon: Zap,
        category: "AI · Monitoring",
        description: "Alerting rules for latency, cost and errors",
        keywords: ["alerting", "alerts", "notifications", "thresholds"],
      },
      {
        href: "/ai-observability/recommendations",
        label: "Routing Recommendations",
        icon: TrendingDown,
        category: "AI · Cost",
        description: "Cheaper/faster model routing suggestions",
        keywords: ["routing", "recommendations", "model routing", "savings"],
      },
      {
        href: "/ai-observability/prompts",
        label: "Prompt Insights",
        icon: Hash,
        category: "AI · Prompts",
        description: "Analytics on prompt performance",
        keywords: ["prompts", "prompt analytics", "insights"],
      },
      {
        href: "/ai-observability/playground",
        label: "Prompt Playground",
        icon: TestTube,
        category: "AI · Prompts",
        description: "Test prompts against live models",
        keywords: ["playground", "prompt testing", "sandbox", "compare models"],
      },
      {
        href: "/ai-observability/evaluations",
        label: "Evaluations",
        icon: ShieldCheck,
        category: "AI · Quality",
        description: "Score output quality with automated evals",
        keywords: ["evaluations", "evals", "llm-as-a-judge", "auditing", "score"],
      },
    ],
  },
  {
    label: "Operations",
    section: "operations",
    items: [
      {
        href: "/dashboards/cost",
        label: "Billing & Cost Explorer",
        icon: DollarSign,
        category: "Cost & FinOps",
        description: "Cloud spend breakdown and forecasts",
        aliases: ["cost explorer", "invoice"],
        keywords: ["cost explorer", "billing", "spend", "invoice", "budget"],
      },
      {
        href: "/cost-savings",
        label: "Savings & Waste",
        icon: TrendingDown,
        category: "Cost & FinOps",
        description: "Find idle resources and savings opportunities",
        keywords: ["finops", "waste", "savings", "idle", "unused", "reserved"],
      },
      {
        href: "/dashboards/alerts",
        label: "Alerts & Alarms",
        icon: Bell,
        category: "Automation & Actions",
        description: "CloudWatch alarms and notifications",
        keywords: ["alarms", "alerts", "notifications", "thresholds"],
      },
      {
        href: "/actions",
        label: "Action History",
        icon: History,
        category: "Automation & Actions",
        description: "Log of automated and manual executions",
        keywords: ["history", "executions", "automation", "audit", "runs"],
      },
      {
        href: "/profile?tab=team",
        label: "Team & Access (IAM)",
        icon: ShieldCheck,
        category: "Access & Team",
        description: "Manage members, roles and permissions",
        aliases: ["users", "permissions", "roles"],
        keywords: [
          "iam",
          "team",
          "members",
          "users",
          "rbac",
          "roles",
          "credentials",
          "access",
          "invite",
        ],
      },
      {
        href: "/settings/ai-observability",
        label: "AI Observability Setup",
        icon: Key,
        category: "AI · Setup",
        description: "Create ingest keys and connect the SDK",
        aliases: [
          "ingest key",
          "ingest keys",
          "api key",
          "sdk key",
          "connect ai",
        ],
        keywords: [
          "ingest key",
          "ingest keys",
          "ingestion",
          "api key",
          "api keys",
          "token",
          "secret",
          "sdk",
          "instrument",
          "connect",
          "onboarding",
          "telemetry",
          "setup",
          "ai observability settings",
        ],
      },
      {
        href: "/settings/ai-keys",
        label: "AI Provider Keys",
        icon: Brain,
        category: "AI · Setup",
        description: "Store OpenAI/Anthropic keys for playground & evals",
        aliases: ["byok", "llm keys", "model keys"],
        keywords: [
          "provider keys",
          "openai key",
          "anthropic key",
          "api keys",
          "ai settings",
          "credentials",
          "llm keys",
        ],
      },
      {
        href: "/settings/reports",
        label: "Email Reports",
        icon: Mail,
        category: "Reports",
        description: "Schedule recurring email reports",
        keywords: ["reports", "email", "schedule", "digest", "pdf"],
      },
      {
        href: "/settings/aws",
        label: "Connect AWS",
        icon: Settings,
        category: "Cloud Connections",
        description: "Link an AWS account via CloudFormation",
        keywords: ["connect aws", "cloudformation", "account", "integration"],
      },
      {
        href: "/settings/azure",
        label: "Connect Azure",
        icon: Settings,
        category: "Cloud Connections",
        description: "Link an Azure subscription",
        keywords: [
          "connect azure",
          "service principal",
          "active directory",
          "subscription",
        ],
      },
      {
        href: "/settings/gcp",
        label: "Connect GCP",
        icon: Settings,
        category: "Cloud Connections",
        description: "Link a Google Cloud project",
        keywords: [
          "connect gcp",
          "google cloud",
          "service account",
          "project",
        ],
      },
      {
        href: "/settings/github",
        label: "Connect GitHub",
        icon: Github,
        category: "Cloud Connections",
        description: "Link repositories for IaC scanning",
        keywords: ["connect github", "repository", "iac", "git", "terraform"],
      },
    ],
  },
  {
    label: "Simulation",
    section: "simulation",
    items: [
      {
        href: "/simulations/live-canvas",
        label: "Live Infrastructure",
        icon: Server,
        category: "Simulation",
        description: "Interactive canvas of your running infrastructure",
        keywords: ["simulations", "live", "running", "canvas", "topology"],
      },
      {
        href: "/simulations",
        label: "Simulation History",
        icon: History,
        category: "Simulation",
        description: "Past simulation runs and their results",
        keywords: ["simulations", "history", "past", "runs"],
      },
      {
        href: "/simulation",
        label: "New Simulation",
        icon: TestTube,
        category: "Simulation",
        description: "Start a new what-if infrastructure simulation",
        keywords: ["simulation", "sandbox", "test", "experiment", "lab", "new"],
      },
    ],
  },
];

const allNavItems = navGroups.flatMap((group) =>
  group.items.map((item) => ({
    ...item,
    group: group.label,
    category: item.category || group.label,
    // System-admin-only items never surface to normal users in the service
    // directory or command palette.
    systemAdminOnly: item.systemAdminOnly,
    // Fold provider names (e.g. "Blob Storage" for S3) into aliases here so the
    // search engine stays a pure, registry-free ranker.
    aliases: [...(item.aliases || []), ...providerAliases(item.href)],
  })),
);

const seenHrefs = new Set<string>();
export const searchableNavItems = allNavItems.filter((item) => {
  if (seenHrefs.has(item.href)) return false;
  seenHrefs.add(item.href);
  return true;
});

export const serviceDirectoryItems = searchableNavItems;
